id: 48aa23435f9147e4816bae1bc99a6cab
initial_creation_type: ocr
source_metadata:
  volumes:
    e03e0320e40c4c3483b2ba60ffe2e073:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ''
      total_pages: 1953
      volume_number: 27
